# Generated by Django 5.1.1 on 2024-10-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_bid_unique_together_auctionhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bidder',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='item',
        ),
        migrations.DeleteModel(
            name='AuctionHistory',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
